services:
#    samples_index.example:
#        class: Samples\IndexBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

     samples.util.exporter.pdf:
         class: Samples\IndexBundle\Exporter\PdfExporter
         arguments: ["@templating"]
