<?php

namespace Samples\ProgramadoresBundle\Manager;

use Doctrine\ORM\EntityRepository;

/**
 * LenguajeProgramacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LenguajeProgramacionRepository extends EntityRepository {

    public function findAllDQL() {

        $dql = 'SELECT s FROM SamplesProgramadoresBundle:LenguajeProgramacion s ORDER BY s.nombre';

        return $dql;
    }

    public function findAll() {

        $dql = $this->findAllDQL();

        $query = $this->getEntityManager()->createQuery($dql);

        $result = $query->getResult();

        return $result;
    }

}
