<?php

namespace Samples\ProgramadoresBundle\Manager;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramadorRepository extends EntityRepository
{
}
