<?php

namespace Samples\ProgramadoresBundle\Manager;

use Doctrine\ORM\EntityRepository;

/**
 * SistemaOperativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaOperativoRepository extends EntityRepository {

    public function findAllDQL() {

        $dql = 'SELECT s FROM SamplesProgramadoresBundle:SistemaOperativo s ORDER BY s.nombre';

        return $dql;
    }

    public function findAll() {

        $dql = $this->findAllDQL();

        $query = $this->getEntityManager()->createQuery($dql);

        $result = $query->getResult();

        return $result;
    }

}
