<?php

namespace \Samples\PropinasEstudiantisBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * PagamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagamentoRepository extends EntityRepository
{
}
